-- ════════════════════════════════════════════
-- 003: Staff Invite System
-- Run in Supabase SQL Editor after 002
-- ════════════════════════════════════════════

-- Store Invites: stores invite tokens generated by owners/admins
CREATE TABLE IF NOT EXISTS store_invites (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  store_id    UUID REFERENCES stores(id) ON DELETE CASCADE NOT NULL,
  created_by  UUID REFERENCES profiles(id) NOT NULL,
  token       TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(16), 'hex'),
  role        TEXT NOT NULL DEFAULT 'cashier'
                CHECK (role IN ('admin', 'cashier')),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '7 days',
  used_by     UUID REFERENCES profiles(id),
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_store_invites_token ON store_invites(token);
CREATE INDEX IF NOT EXISTS idx_store_invites_store ON store_invites(store_id);

-- RLS for store_invites
ALTER TABLE store_invites ENABLE ROW LEVEL SECURITY;

-- Owners/admins can view all invites for their store
CREATE POLICY "Admins can view store invites"
  ON store_invites FOR SELECT
  USING (store_id = get_user_store_id() AND get_user_role() IN ('admin', 'owner'));

-- Owners/admins can create invites
CREATE POLICY "Admins can create store invites"
  ON store_invites FOR INSERT
  WITH CHECK (store_id = get_user_store_id() AND get_user_role() IN ('admin', 'owner'));

-- Owners/admins can delete invites (revoke)
CREATE POLICY "Admins can delete store invites"
  ON store_invites FOR DELETE
  USING (store_id = get_user_store_id() AND get_user_role() IN ('admin', 'owner'));

-- Anyone can read an invite by token (for registration flow — no auth needed)
CREATE POLICY "Public can read invite by token"
  ON store_invites FOR SELECT
  USING (true);
